site_name: repath
site_description: Scalable Vector Graphics Manipulation
site_author: Konstantinos Kaloutas
site_url: https://repath.studio/
copyright: 2024 Â© Repath Studio

repo_url: https://github.com/re-path/studio
repo_name: re-path/studio

extra_css:
  - assets/stylesheets/extra.css
  
extra_javascript:
  - assets/javascripts/snap.svg-min.js

theme:
  name: material
  custom_dir: theme
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.expand
  - navigation.indexes
  - announce.dismiss
  - navigation.top
  - navigation.instant
  - navigation.footer
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
  palette:
    primary: pink-700
    accent: pink
  font: false
  
nav:
  - Home: index.md
  - Get Studio:
    - get-studio/download.md
    - get-studio/build-from-source.md
  - Docs:
    - docs/shortcuts.md
  - Contribute:
    - contribute/CONTRIBUTING.md
    - CLA: contribute/cla.md
  - Changelog: roadmap/changelog.md

extra:
  generator: false
  social:
  - icon: fontawesome/solid/at
    link: mailto:contact@repath.studio
    name: Email us
  - icon: fontawesome/brands/discord
    link: https://discord.gg/yzjY6W6ame
  - icon: fontawesome/brands/twitter
    link: https://www.twitter.com/repath_studio/
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/repath.studio/
  - icon: fontawesome/brands/github
    link: https://github.com/re-path/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences 
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - glightbox
  - social:
      cards_layout_options:
        font_family: Sora
        background_color: pink
